/**
 * EDIT-OS — Core Domain
 * Fuente de verdad para tipos y entidades de orquestación global.
 */
export type {
  Brand,
  Client,
  ClientId,
  ContingencyPlan,
  Event,
  EventId,
  EventStatus,
  OrchestrationState,
  PlanVariant,
  RiskCategory,
  RiskLevel,
  RiskProfile,
  RiskSignal,
  TimelineBlock,
  TimelineBlockId,
  TimelineBlockStatus,
  Vendor,
  VendorCategory,
  VendorId,
  ActionExecutionRecord,
  ActionExecutionStatus,
  WorkflowAction,
  WorkflowProposal,
  WorkflowProposalId,
  WorkflowProposalStatus,
  UserProfile,
  UserRole,
  TeamMember,
  NotificationPreferences,
  IntegrationConfig,
  BillingPlan,
  ProfileState,
  Message,
  MessageId,
  MessageThread,
  DocumentId,
  DocumentTreeNode,
  DocumentVisibility,
  EventDocument,
  EventFolder,
  FolderId,
  SchedulerRunRecord,
  SchedulerStatus,
  AutoApproveRule,
  OrchestrationDecision,
  OrchestrationLog,
  OrchestrationPolicy,
  PolicyProposalContext,
  PolicyThresholds,
} from './types/index.js';
export { DEFAULT_AUTO_APPROVE_RULES, DEFAULT_THRESHOLDS } from './policy-defaults.js';
