/**
 * EDIT-OS — Core Domain
 * Fuente de verdad para tipos y entidades de orquestación global.
 */
export type {
  Brand,
  Client,
  ClientId,
  ContingencyPlan,
  Event,
  EventId,
  EventStatus,
  OrchestrationState,
  PlanVariant,
  RiskCategory,
  RiskLevel,
  RiskProfile,
  RiskSignal,
  TimelineBlock,
  TimelineBlockId,
  TimelineBlockStatus,
  Vendor,
  VendorCategory,
  VendorId,
  ActionExecutionRecord,
  ActionExecutionStatus,
  WorkflowAction,
  WorkflowProposal,
  WorkflowProposalId,
  WorkflowProposalStatus,
  UserProfile,
  UserRole,
  TeamMember,
  NotificationPreferences,
  IntegrationConfig,
  BillingPlan,
  ProfileState,
  Message,
  MessageId,
  MessageThread,
} from './types/index.js';
